# Generated by Django 2.0.7 on 2019-02-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('room_code', models.CharField(max_length=200)),
                ('date_generated', models.DateTimeField(verbose_name='date generated')),
                ('server_ip', models.CharField(max_length=200)),
            ],
        ),
    ]
