# Generated by Django 2.0.7 on 2019-02-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancemaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='default room name', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='server_ip',
            field=models.CharField(default='0.0.0.0', max_length=200),
        ),
    ]
