# Generated by Django 2.0.7 on 2019-02-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancemaker', '0002_auto_20190219_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='instance_id',
            field=models.CharField(default='i-0', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='-1', max_length=200),
        ),
    ]
